openapi: 3.0.1
info:
  title: Hyperliquid
  description: API for interacting with the Hyperliquid Decentralized Exchange (DEX).
  version: '0.1.0' # Use standard SemVer notation

servers:
  - url: https://api.hyperliquid.xyz
    description: Hyperliquid Mainnet API endpoint
  - url: https://api.hyperliquid-testnet.xyz
    description: Hyperliquid Testnet API endpoint
  - url: http://localhost:3001
    description: Local development endpoint

paths:
  /info:
    post:
      summary: Retrieve the Mid-Price (mid) for all actively traded perpetuals.
      operationId: getAllMids
      
      requestBody:
        description: Request body to specify the type of query.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  # Use const instead of enum if only one value is currently supported. 
                  # This provides cleaner documentation for single-purpose fields.
                  const: allMids 
              required:
                - type
            example:
              type: allMids

      responses:
        '200':
          description: Successful response returning coin symbols mapped to mid-prices.
          content:
            application/json:
              schema:
                type: object
                # The response structure is a map (dictionary) where keys are coin symbols (e.g., APE, ARB).
                additionalProperties:
                  $ref: '#/components/schemas/FloatString'
              example:
                APE: "4.36255"
                ARB: "1.22965"
                AVAX: "18.3695"
        '400':
          description: Bad request (e.g., missing required fields in request body).
        '500':
          description: Internal server error (e.g., issues retrieving data).

components:
  schemas:
    FloatString:
      type: string
      description: A price or quantity represented as a string to maintain full floating-point precision.
      example: "4.36255"
